export const Theme = {
  colors: {
    primaryTeal: '#0E7490',
    accentBlue: '#0E74F6',
    successGreen: '#22C55E',
    warningYellow: '#EAB308',
    errorRed: '#EF4444',
    textDark: '#0F172A',
    textMuted: '#64748B',
    surface: '#F8FAFC',
    surfaceAlt: '#F1F5F9',
    border: '#E2E8F0',
    backgroundLight: '#FFFFFF',
    backgroundDark: '#1E293B',
    slate700: '#334155',
    slate800: '#1E293B',
    slate900: '#0F172A',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    full: 9999,
  },
  typography: {
    fontFamily: {
      regular: 'System',
      mono: 'Courier New',
    },
    fontSize: {
      xs: 10,
      sm: 12,
      base: 14,
      lg: 16,
      xl: 18,
      '2xl': 20,
      '3xl': 24,
      '4xl': 28,
      '5xl': 32,
    },
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.25,
      shadowRadius: 24,
      elevation: 8,
    },
  },
};
